config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  root :to => 'users#home'
  devise_for :users
  resources :books do
  	resources :favorites, only: [:create, :destroy, :index]
  	resources :post_comments, only: [:create, :destroy, :edit, :update]
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: {maximum: 200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!, only: [:show, :edit, :update, :delete, :index]
	before_action :correct_user, only: [:edit, :update]
  protected
  def after_sign_in_path_for(resource)
    user_path(@user)
  end
  def after_sign_up_path_for(resource)
    user_path(@user)
  end
  # def after_sign_out_path_for(resource)
  #   new_user_session_path # ログアウト後に遷移するpathを設定
  # end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
    	@books = Book.all
    	@book = Book.new
       	# @book = Book.find(params[:id])
       	# @user = User.find(params[:id])
    end
    def create
  		@book = Book.new(book_params)
  		@book.user_id = current_user.id
  		if @book.save
  		   flash[:notice] = "You have creatad book successfully."
  	   	   redirect_to book_path(@book)
  	   	else
  	   	   @books = Book.all
  	   	   render "index"
  	   	end
    end
    def show
    	@book = Book.find(params[:id])
    	@newbook = Book.new
      @post_comment = PostComment.new
      # @favorite = Favorite.new
      # @comments = @book.comments
    	# @user = User.find(params[:id])
    end
    def edit
  		@book = Book.find(params[:id])
      # @comment = Comment.find(params[:id])
  	end
  	def update
  		@book = Book.find(params[:id])
  		if @book.update(book_params)
  		   flash[:notice] = "You have updated book successfully."
  		   redirect_to book_path(@book)
  		else
  			render "edit"
  		end
  	end
    def destroy
    	@book = Book.find(params[:id])
    	if @book.destroy
    	   redirect_to books_path
    	else
    		render "show"
    	end
    end
  	private
  	def book_params
  		params.require(:book).permit(:title, :body, :user_id, :name, :profile_image) #:user_id不要？
  	end
    def correct_user
     @book = Book.find(params[:id])
     if current_user != @book.user
     	redirect_to books_path
	   end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def index
		@book = Book.find(params[:book_id])
	end
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_to book_path(book)
	end
	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_to book_path(book)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.user_id = current_user.id
		comment.book_id = book.id
		# user = User.find_by(id: @book.user_id)
		comment.save
		redirect_to book_path(book)
	end
	def edit
		@book = Book.find(params[:book_id])
		@comment = @book.post_comments.find(params[:id])
		# @comment = Post_comment.find(params[:id])
		@comment.user_id = current_user.id
	end
	def update
		@book = Book.find(params[:book_id])
		@comment = @book.post_comments.find(params[:id])
		@comment.update(post_comment_params)
		redirect_to book_path(@book)
	end
	def destroy
		@book = Book.find(params[:book_id])
		@comment = @book.post_comments.find(params[:id])
		@comment.destroy
		redirect_to book_path(@book)
	end
	private
	def post_comment_params
		params.require(:post_comment).permit(:user_id, :book_id, :comment)
	end
    def correct_user

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end
  def about
  end
  def index
  	@users = User.all
   	@book = Book.new
   	# @user = User.find(params[:id])
  end
  def show
  	@user = User.new
  	@user = User.find(params[:id])
  	@books = Book.where(user_id: params[:id])
  	# @books = current_user.books.all
   	# @books = Book.find(params[:id])
  	@book = Book.new
  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "You have updated user successfully."
  	    redirect_to user_path(@user.id)
  	else
  	 	render "edit"
  	end
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :user_id) #user_id不要？
  end
  def correct_user
    user = User.find(params[:id])
  	if current_user != user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>
	<div class="field row" id="book_title">
		<%= f.label :title %>
		<%= f.text_field :title, class:"col-xs-12 book_title" %>
	</div>
	<div class="field row" id="book_body">
		<%= f.label :body, "Opinion" %>
		<%= f.text_area :body, class:"col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
	</div>

<% end %>


<%= link_to "Show", book_path(@book), class:"book_id" %>
|
<%= link_to "Back", books_path, class:"back" %>
</div>
<div class="col-md-3">
</div>
</div>
</div>
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<div class="container">

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
<div class="col-xs-3">
	<h2>User info</h2>
<!--     <h3 class="profile-name"></h3> -->
	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
		<table class="table">
			<tbody>
				<tr>
					<th>name</th>
					<th><%= current_user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= current_user.introduction %></th>
				</tr>
			</tbody>
		</table>
		<div class="row">
		<%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_id" %>
		</div>

<h2>New Book</h2>
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
	<div class="field row" id="book_title">
		<%= f.label :title %>
		<%= f.text_field :title, class:"col-xs-12 book_title" %>
	</div>
	<div class="field row" id="book_body">
		<%= f.label :body, "Opinion" %>
		<%= f.text_area :body, class:"col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
<% end %>
</div>

<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<% @books.each do |book| %>
	<tbody>
		<tr>
			<td><%= link_to user_path(book.user) do %><%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", size:'30x30' %><% end %>
				</td>
			<td><%= link_to book.title, book_path(book) %></td>
			<td><%= book.body %></td>
			<td><%= book.favorites.count %> いいね</td>
		</tr>
	</tbody>
	<% end %>
</table>
</div>

	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>


app/views/books/show.html.erb
<div class="container">

<%= flash[:notice] %>
<div class="row">
<div class="col-xs-3">

	<h2>User info</h2>
<!--     <h3 class="profile-name"></h3> -->
	<%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

		<table class="table">
			<tbody>
				<tr>
					<th>name</th>
					<th><%= @book.user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= @book.user.introduction %></th>
				</tr>
			</tbody>
		</table>
		<div class="row">
		<%= link_to "", edit_user_path(@book.user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_id" %>
		</div>

<h2>New Book</h2>

<%= form_for(@newbook) do |f| %>
<% if @newbook.errors.any? %>
  <div id="error_explanation">
    <h2><%= @newbook.errors.count %>errors prohibited this book from being saved:</h2>

    <ul>
    <% @newbook.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
	<div class="field row" id="book_title">
		<%= f.label :title %>
		<%= f.text_field :title, class:"col-xs-12 book_title" %>
	</div>
	<div class="field row" id="book_body">
		<%= f.label :body, "Opinion" %>
		<%= f.text_area :body, class:"col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>

<% end %>
</div>

<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table">
	<tbody>
		<tr>
			<td><%= link_to user_path(@book.user) do %><%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", size:'30x30', class:"attachment user profile_image fallback" %><br>
				<%= @book.user.name %><% end %>
			</td>
			<td><%= @book.title %></td>
			<td><%= @book.body %></td>
			<td>
				<% if @book.favorited_by?(current_user) %>
				<li>
					<%= link_to book_favorite_path(@book), method: :delete do %>
						<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					<% end %>
					<%= @book.favorites.count %> いいね
				</li>
				<% else %>
				<li>
					<%= link_to book_favorites_path(@book), method: :post do %>
					<i class="fa fa-heart-o" aria-hidden="true"></i>
					<% end %>
					<%= @book.favorites.count %>　いいね
				</li>
				<% end %>
			</td>
			 <% if @book.user.id == current_user.id %>
			<td><%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success edit_book_id" %></td>
			<td><%= link_to "Destroy", book_path(@book), class:"btn-sm btn-danger destroy_book_id", method: :delete, data: {confirm: "本当に消しますか？"}  %></td>
			<% end %>
		</tr>
	</tbody>
</table>
<h3>Book Comments</h3>
<table class="table">
	<thead>
		<tr>
			<th>name</th>
			<th>comment</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<% @book.post_comments.each do |post_comment| %>
	<tbody>
		<tr>
			<td><%= post_comment.user.name %></td>
			<td><%= post_comment.comment %></td>
			<% if post_comment.user.id == current_user.id %>
			<td><%= link_to "Edit", edit_book_post_comment_path(@book.id, post_comment.id), class:"btn-sm btn-success edit_book_id" %></td>
			<td><%= link_to "Destroy", book_post_comment_path(@book.id, post_comment.id), class:"btn-sm btn-danger destroy_book_id", method: :delete, data: {confirm: "本当に消しますか？"}  %></td>
			<% end %>
		</tr>
	</tbody>
	<% end %>
</table>
<%= form_for [@book, @post_comment] do |f| %>
	<div class="row">
		<div class="col-sm-12">
			<%= f.text_area :comment, class: "form-control",placeholder: "コメントをここに入力してください" %>
		</div>
	</div>
	<%= f.submit "push", class: "btn btn-base-1 mt-20 pull-right" %>
<% end %>
</div>

	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>

app/views/favorites/index.html.erb
<h2>いいね一覧</h2>
<% @book.favorites.each do |favorite| %>
<%= favorite.user.name %>
<% end %>

app/views/home/about.html.erb
<div class="container">
	<div class="row">
	  <div class='top-message col-md-offset-3 col-md-6'>
	    <h1>Welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>!</h1>
	   </div>
	</div>
</div>
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/50e1df26d8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse"><!-- /header -->
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li> <!-- ログインした場合 -->
              <%= link_to " Home",  user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
            </li>
            <li>
              <%= link_to " Users", users_path, class:"glyphicon glyphicon-user users" %>
            </li>
            <li>
              <%= link_to " Books", books_path, class:"glyphicon glyphicon-book books" %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, class:"glyphicon glyphicon-log-out logout", method: :delete %>
            </li> <!-- ログインした場合終わり -->
            <% else %>
            <li> <!-- 未ログインの場合 -->
              <%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %>
            </li>
            <li>
              <%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %>
            </li>
            <li>
              <span ></span>
              <%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %>
            </li> <!-- 未ログインの場合終わり -->
            <% end %>
          </ul>
        </nav>
      </div>
    </header><!-- /header -->
    <div class="body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/post_comments/edit.html.erb
<h2>Comment Edit</h2>

<%= form_for [@book, @comment] do |f| %>
	<div class="row">
		<div class="col-sm-6">
			<%= f.text_area :comment, class: "form-control",placeholder: "コメントをここに入力してください" %>
		</div>
	</div>
	<%= f.submit "push", class: "btn btn-base-1 mt-20 pull-left" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

	<h2>User info</h2>
		<%= f.label :name %>
	<div class="field" id="user_name">
		<%= f.text_field :name %>
	</div>
		<%= f.label :image %>
	<div>
		 <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
	</div>
		<%= f.label :introduction %>
	<div class="field" id="user_introduction">
		<%= f.text_area :introduction %>
	</div>
	<div class="actions">
		<%= f.submit 'Update User' %>
	</div>

<% end %>
</div>
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/home.html.erb
<div class="container">
<%= flash[:notice] %>
  <div class="row">

    <div class="row">
      <div class='top-message col-md-offset-3 col-md-6'>
        <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
              <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
              <p>you can share and exchange  your opinions , inpressions , and emotions</p>
              <p> about varioius books!</p>

        <div class="btn-wrapper">
          <div class="row">
             <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
          </div>
          <div class="row">
            <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


  <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<div class="container">
	<div class="row">

<div class="col-xs-3">
	<h2>User info</h2>
<!--     <h3 class="profile-name"></h3> -->
	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
		<table class="table">
			<tbody>
				<tr>
					<th>name</th>
					<th><%= current_user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= current_user.introduction %></th>
				</tr>
			</tbody>
		</table>
		<div class="row">
		<%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_id" %>
		</div>

<h2>New Book</h2>
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
	<div class="field row" id="book_title">
		<%= f.label :title %>
		<%= f.text_field :title, class:"col-xs-12 book_title" %>
	</div>
	<div class="field row" id="book_body">
		<%= f.label :body, "Opinion" %>
		<%= f.text_area :body, class:"col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
<% end %>
</div>

<div class="col-xs-9">
	<h2>Users</h2>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th></th>
				</tr>
			</thead>
			<% @users.each do |user| %>
			<tbody>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", size:'30x30' %></td>
					<td><%= user.name %></td>
					<td><%= link_to "Show", user_path(user) %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
</div>
</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>



app/views/users/show.html.erb
<div class="container">

<%= flash[:notice] %>
<div class="row">
<div class="col-xs-3">
	<h2>User info</h2>
<!--     <h3 class="profile-name"></h3> -->
	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
		<table class="table">
			<tbody>
				<tr>
					<th>name</th>
					<th><%= @user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= @user.introduction %></th>
				</tr>
			</tbody>
		</table>
		<div class="row">
		<%= link_to "", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_id" %>
		</div>


<h2>New Book</h2>
<%= form_for(@book) do |f| %>
	<% if @book.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>

	    <ul>
	    <% @book.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<div class="field row" id="book_title">
		<%= f.label :title %>
		<%= f.text_field :title, class:"col-xs-12 book_title" %>
	</div>
	<div class="field row" id="book_body">
		<%= f.label :body, "Opinion" %>
		<%= f.text_area :body, class:"col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
<% end %>
</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<% @books.each do |book| %>
				<tbody>
					<tr>
						<td><%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", size:'30x30' %></td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div> <!-- class="col-xs-9" -->
	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>